// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx9f_nqZepETYcMIRG3fpCJszl__R1hzw',
    appId: '1:814834178622:web:c2387c6d477e757322cf6f',
    messagingSenderId: '814834178622',
    projectId: 'fb01test',
    authDomain: 'fb01test.firebaseapp.com',
    storageBucket: 'fb01test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAur8z3j3Y4eXZk2UN_JfgIv6pQ0fPX3zM',
    appId: '1:814834178622:android:db2f0697cfebeaa222cf6f',
    messagingSenderId: '814834178622',
    projectId: 'fb01test',
    storageBucket: 'fb01test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsKpyP1VZyLGk_971mE4tQ66L1ruZCVAM',
    appId: '1:814834178622:ios:1d9465618cd84b2b22cf6f',
    messagingSenderId: '814834178622',
    projectId: 'fb01test',
    storageBucket: 'fb01test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsKpyP1VZyLGk_971mE4tQ66L1ruZCVAM',
    appId: '1:814834178622:ios:1d9465618cd84b2b22cf6f',
    messagingSenderId: '814834178622',
    projectId: 'fb01test',
    storageBucket: 'fb01test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx9f_nqZepETYcMIRG3fpCJszl__R1hzw',
    appId: '1:814834178622:web:b8b4c6f5b43654bb22cf6f',
    messagingSenderId: '814834178622',
    projectId: 'fb01test',
    authDomain: 'fb01test.firebaseapp.com',
    storageBucket: 'fb01test.firebasestorage.app',
  );
}
